package script.model;

import java.util.List;

public abstract class ScriptFuncLib {
    private static ScriptFunc[] FUNCS;

    private static boolean initialized = false;

    private static ScriptField p(int index) {
        return p("p" + index, "unknown");
    }
    
    private static ScriptField p(String typeAndName) {
        return new ScriptField(typeAndName);
    }

    private static ScriptField p(String name, String type) {
        return new ScriptField(name, type);
    }

    private static ScriptFunc putUnknownFunc(int idx, String internalName, int inputs) {
        return putUnknownFunc(idx, internalName, "unknown", inputs);
    }

    private static ScriptFunc putUnknownFunc(int idx, String internalName, String returnType, int inputs) {
        ScriptField[] inputList = new ScriptField[inputs];
        for (int i = 0; i < inputs; i++) {
            inputList[i] = p(i+1);
        }
        return putUnknownFunc(idx, internalName, returnType, inputList);
    }

    private static ScriptFunc putUnknownFunc(int idx, String internalName, String returnType, ScriptField... inputList) {
        ScriptFunc func = new ScriptFunc(null, returnType, internalName, inputList);
        return putFuncWithIdx(idx, func);
    }

    private static ScriptFunc putUnknownFunc(int idx, int inputs) {
        return putUnknownFunc(idx, null, inputs);
    }

    private static ScriptFunc putFuncWithIdx(int idx, ScriptFunc func) {
        func.idx = idx;
        func.funcspace = idx / 0x1000;
        FUNCS[idx] = func;
        return func;
    }

    public static ScriptFunc get(int idx, List<StackObject> params) {
        if (FUNCS[idx] == null) {
            System.err.println("Unknown Function call: " + String.format("%04X", idx));
            return null;
        }
        return FUNCS[idx];
    }

    public static void initialize() {
        if (initialized) {
            return;
        }
        initialized = true;
        FUNCS = new ScriptFunc[0x10000];
        putFuncWithIdx(0x0000, new ScriptFunc("waitFrames", "unknown", null, p("frames", "int")));
        putUnknownFunc(0x0001, 1); // noclip: load character/summon/weapon etc
        putUnknownFunc(0x0002, 3);
        putFuncWithIdx(0x0003, new ScriptFunc("attachToLevelPart", "unknown", null, p("partIndex", "int")));
        putFuncWithIdx(0x0004, new ScriptFunc("attachToMapGroup", "unknown", null, p("groupIndex", "int")));
        putFuncWithIdx(0x0005, new ScriptFunc("applyTransform", "unknown", null, true));
        putUnknownFunc(0x0006, 3);
        putUnknownFunc(0x0007, 1);
        putUnknownFunc(0x0010, 0);
        putUnknownFunc(0x0011, 2);
        putUnknownFunc(0x0012, 2);
        putFuncWithIdx(0x0013, new ScriptFunc("setPosition", "unknown", null, p("x", "float"), p("y", "float"), p("z", "float")));
        putUnknownFunc(0x0015, 3);
        putFuncWithIdx(0x0016, new ScriptFunc("setMotionSpeed", "unknown", null, p("speed", "float")));
        putUnknownFunc(0x0017, 1); // noclip: set motion threshold/radius, used for collision and checking if a destination is reached
        putUnknownFunc(0x0018, 3);
        putFuncWithIdx(0x0019, new ScriptFunc("startRotation", "unknown", null, p("activeBits", "int"), p("flags", "int"), p("targetObjectIndex", "int"))); // see noclip for flags
        putUnknownFunc(0x001A, 0);
        putUnknownFunc(0x001B, 0);
        putUnknownFunc(0x001C, 2);
        putFuncWithIdx(0x001D, new ScriptFunc("setRotationTiming", "unknown", null, p("currTime?", "float"), p("duration?", "int")));
        putUnknownFunc(0x001F, null, "float", 0);
        putUnknownFunc(0x0020, 0);
        putUnknownFunc(0x0021, 1);
        putFuncWithIdx(0x0023, new ScriptFunc("setVelocityYaw", "unknown", null, p("angle", "float"))); // Never used by the game
        putFuncWithIdx(0x0024, new ScriptFunc("setVelocityPitch", "unknown", null, p("angle", "float"))); // Never used by the game
        putUnknownFunc(0x0025, 1); // noclip: 25-7 set a contextually-dependent vector, sometimes euler angles, 26/27 are never used by the game
        putFuncWithIdx(0x0028, new ScriptFunc("setRotationTarget1", "unknown", null, p("angle", "float")));
        putFuncWithIdx(0x0029, new ScriptFunc("setRotationTarget2", "unknown", null, p("angle", "float")));
        putFuncWithIdx(0x002A, new ScriptFunc("setRotationTarget3", "unknown", null, p("angle", "float")));
        putUnknownFunc(0x002B, 1);
        putUnknownFunc(0x002C, 1);
        putUnknownFunc(0x002D, 1);
        putUnknownFunc(0x002E, 1);
        putUnknownFunc(0x002F, 1);
        putUnknownFunc(0x0030, 1);
        putUnknownFunc(0x0033, 1);
        putUnknownFunc(0x0034, 1);
        putUnknownFunc(0x0035, 1);
        putUnknownFunc(0x0036, 1);
        putUnknownFunc(0x0037, 1);
        putUnknownFunc(0x0038, null, "float", 1);
        putUnknownFunc(0x0039, null, "float", 1);
        putUnknownFunc(0x003A, null, "float", 1);
        putUnknownFunc(0x003D, 0);
        putUnknownFunc(0x003F, 0);
        putFuncWithIdx(0x0042, new ScriptFunc("linkFieldToBattleActor?", "unknown", null, p("actor")));
        putUnknownFunc(0x0043, 0);
        putUnknownFunc(0x0044, 0);
        putUnknownFunc(0x0046, 0);
        putUnknownFunc(0x0047, 0);
        putUnknownFunc(0x004C, 1);
        putFuncWithIdx(0x004D, new ScriptFunc("controllerButtonPressed1?", "bool", null, p("controllerButton")));
        putUnknownFunc(0x0050, 1);
        putFuncWithIdx(0x0051, new ScriptFunc("controllerButtonPressed2?", "bool", null, p("controllerButton")));
        putUnknownFunc(0x0054, 6); // noclip: collision detection
        putUnknownFunc(0x0055, 1); // noclip: collision detection
        putUnknownFunc(0x0056, 1); // noclip: collision detection
        putUnknownFunc(0x0057, 3); // noclip: collision detection
        putUnknownFunc(0x0058, 2); // noclip: collision detection
        putUnknownFunc(0x0059, 3); // noclip: collision detection
        putUnknownFunc(0x005A, 1); // noclip: collision detection
        putUnknownFunc(0x005C, 1); // noclip: collision detection
        putUnknownFunc(0x005D, 0);
        putUnknownFunc(0x005E, 0);
        putUnknownFunc(0x005F, 0);
        putUnknownFunc(0x0060, 1);
        putUnknownFunc(0x0061, 1); // noclip: collision detection
        putUnknownFunc(0x0062, 1); // noclip: collision detection
        putUnknownFunc(0x0063, 1); // noclip: collision detection
        putFuncWithIdx(0x0064, new ScriptFunc("displayFieldString", "unknown", null, p("boxIndex", "int"), p("string")));
        putFuncWithIdx(0x0065, new ScriptFunc("positionText", "unknown", null, p("boxIndex", "int"), p("x?", "int"), p("y?", "int"), p("alignment?", "textAlignment")));
        putUnknownFunc(0x0066, 2);
        putUnknownFunc(0x0069, 3);
        putUnknownFunc(0x006A, 2);
        putUnknownFunc(0x006B, 1);
        putUnknownFunc(0x006C, 1);
        putUnknownFunc(0x006D, 1);
        putUnknownFunc(0x006E, 1);
        putFuncWithIdx(0x006F, new ScriptFunc("setAllRotationRate1", "unknown", null, p("rate", "float")));
        putFuncWithIdx(0x0070, new ScriptFunc("setAllRotationRate2", "unknown", null, p("rate", "float")));
        putFuncWithIdx(0x0071, new ScriptFunc("setAllRotationRate3", "unknown", null, p("rate", "float")));
        putUnknownFunc(0x0074, 1); // noclip: get/set frames?
        putUnknownFunc(0x0076, 0); // noclip: get object type
        putFuncWithIdx(0x0077, new ScriptFunc("stopObjectMotion", "unknown", null, p("index", "int"))); // Is this object index or motion index?
        putUnknownFunc(0x0078, 1);
        putUnknownFunc(0x007A, 2); // noclip: collision detection
        putUnknownFunc(0x007C, 1);
        putUnknownFunc(0x007D, 1);
        putUnknownFunc(0x007F, 1);
        putUnknownFunc(0x0080, 0); // noclip: getMapPointPosition1()
        putUnknownFunc(0x0081, 0); // noclip: getMapPointPosition2()
        putUnknownFunc(0x0082, 0); // noclip: getMapPointPosition3()
        putUnknownFunc(0x0083, 0); // noclip: getMapPointHeading()
        putUnknownFunc(0x0084, 2);
        putUnknownFunc(0x0085, 1); // noclip: setCollisionRadius()
        putUnknownFunc(0x0086, 0);
        putUnknownFunc(0x0087, 0);
        putUnknownFunc(0x0088, 0);
        putUnknownFunc(0x0089, 0);
        putUnknownFunc(0x008B, 0); // noclip: checking line crossing
        putUnknownFunc(0x008D, 1);
        putUnknownFunc(0x008E, 1); // noclip: setCollisionHeight()
        putUnknownFunc(0x008F, 1);
        putUnknownFunc(0x0090, 0); // noclip: getYaw1()
        putUnknownFunc(0x0091, 0);
        putUnknownFunc(0x0092, 1); // noclip: getYaw2()
        putUnknownFunc(0x0093, 1);
        putFuncWithIdx(0x0094, new ScriptFunc("setGravity", "unknown", null, p("g", "int")));
        putFuncWithIdx(0x0095, new ScriptFunc(p("float"))); // noclip: setRotationYaw()
        putUnknownFunc(0x0096, 1); // noclip: setRotationPitch()
        putUnknownFunc(0x0097, 1);
        putUnknownFunc(0x0098, 2);
        putUnknownFunc(0x009A, 1);
        putUnknownFunc(0x009B, 2);
        putUnknownFunc(0x009D, 2);
        putFuncWithIdx(0x009E, new ScriptFunc("prepareStringIntVariable", "unknown", null, p("boxIndex", "int"), p("varIndex", "int"), p(3), p("value", "int")));
        putUnknownFunc(0x00A2, 5);
        putUnknownFunc(0x00A3, 4);
        putUnknownFunc(0x00A4, 2);
        putUnknownFunc(0x00A5, 2);
        putFuncWithIdx(0x00A6, new ScriptFunc("GetRandomInRange", "int", null, p("maxExclusive", "int")));
        putUnknownFunc(0x00A7, 1); // noclip: setIsNotActive()
        putUnknownFunc(0x00A8, 1); // noclip: setIsActive()
        putFuncWithIdx(0x00A9, new ScriptFunc("GetRandomValue", "int", null, true));
        putUnknownFunc(0x00AA, 1);
        putUnknownFunc(0x00AB, 2);
        putUnknownFunc(0x00AC, 1);
        putUnknownFunc(0x00B1, 1);
        putUnknownFunc(0x00B2, 1);
        putUnknownFunc(0x00B3, 1);
        putUnknownFunc(0x00B4, 1);
        putUnknownFunc(0x00BA, 0);
        putUnknownFunc(0x00BB, 1);
        putUnknownFunc(0x00BC, 1);
        putUnknownFunc(0x00BD, 1);
        putUnknownFunc(0x00BE, 1);
        putUnknownFunc(0x00BF, 1); // \
        putUnknownFunc(0x00C0, 1); // -- Technically these aren't certain (zkrn0300)
        putUnknownFunc(0x00C1, 1); // /
        putUnknownFunc(0x00C2, 1); // noclip: getHeading()
        putUnknownFunc(0x00C4, 0);
        putFuncWithIdx(0x00C5, new ScriptFunc(p("p1", "motion"), p("p2", "motion"), p("p3", "motion"), p("p4", "motion")));
        putUnknownFunc(0x00C6, 0);
        putUnknownFunc(0x00C7, 1);
        putUnknownFunc(0x00C8, 3);
        putUnknownFunc(0x00C9, 1); // noclip: getEntrypoint()
        putFuncWithIdx(0x00CA, new ScriptFunc("addPartyMember", "unknown", null, p("actor")));
        putFuncWithIdx(0x00CB, new ScriptFunc("removePartyMember", "unknown", null, p("actor")));
        putUnknownFunc(0x00CC, 1);
        putUnknownFunc(0x00CE, 1);
        putUnknownFunc(0x00CF, 1);
        putUnknownFunc(0x00D0, 0);
        putUnknownFunc(0x00D1, 0);
        putUnknownFunc(0x00D2, 0);
        putFuncWithIdx(0x00D5, new ScriptFunc("playFieldVoiceLine", "unknown", null, p("voiceFileIndex", "int")));
        putUnknownFunc(0x00D6, 0);
        putUnknownFunc(0x00D7, 0);
        putUnknownFunc(0x00D8, 0);
        putUnknownFunc(0x00D9, 0);
        putUnknownFunc(0x00DA, 0);
        putFuncWithIdx(0x00DB, new ScriptFunc("loadMoveAnimation?", "unknown", null, p("moveAnim")));
        putFuncWithIdx(0x00DC, new ScriptFunc("playLoadedMoveAnimation?", "unknown", null, true));
        putUnknownFunc(0x00DE, 0);
        putFuncWithIdx(0x00DF, new ScriptFunc("playSFX?", "unknown", null, p("sfx")));
        putUnknownFunc(0x00E0, 1);
        putUnknownFunc(0x00E1, 0);
        putUnknownFunc(0x00E2, 1);
        putUnknownFunc(0x00E3, 1);
        putUnknownFunc(0x00E4, 1);
        putUnknownFunc(0x00E6, 1);
        putFuncWithIdx(0x00E7, new ScriptFunc("putPartyMemberInSlot", "unknown", null, p("slot", "int"), p("actor")));
        putUnknownFunc(0x00E8, 3);
        putUnknownFunc(0x00E9, 1);
        putUnknownFunc(0x00EB, 0);
        putUnknownFunc(0x00EC, 1);
        putUnknownFunc(0x00ED, 0);
        putUnknownFunc(0x00EE, 1);
        putUnknownFunc(0x00EF, 1);
        putUnknownFunc(0x00F2, 1);
        putUnknownFunc(0x00F3, 1);
        putUnknownFunc(0x00F4, null, "float", 3);
        putUnknownFunc(0x00F5, 3); // Could also be 0-2, must add up to 3 with 0x0096
        putUnknownFunc(0x00F6, 2);
        putUnknownFunc(0x00F8, 3);
        putUnknownFunc(0x00F9, 0);
        putUnknownFunc(0x00FA, 1);
        putUnknownFunc(0x00FB, 1);
        putUnknownFunc(0x00FD, 3);
        putUnknownFunc(0x00FE, 2);
        putUnknownFunc(0x0100, 3);
        putFuncWithIdx(0x0102, new ScriptFunc("setBgmToLoad?", "unknown", null, p("bgm")));
        putFuncWithIdx(0x0103, new ScriptFunc("unloadBgm?", "unknown", null, p("bgm")));
        putFuncWithIdx(0x0104, new ScriptFunc("playBgm?", "unknown", null, p("bgm")));
        putFuncWithIdx(0x0105, new ScriptFunc("loadBgm?", "unknown", null, true));
        putUnknownFunc(0x0106, 3);
        putUnknownFunc(0x0107, 2);
        putUnknownFunc(0x0108, 5);
        putUnknownFunc(0x0109, 1);
        putUnknownFunc(0x010A, 1);
        putUnknownFunc(0x010B, 2);
        putUnknownFunc(0x010C, 2);
        putUnknownFunc(0x010D, 1);
        putUnknownFunc(0x010E, 0);
        putUnknownFunc(0x010F, 4);
        putUnknownFunc(0x0110, 1);
        putUnknownFunc(0x0111, 0);
        putUnknownFunc(0x0112, 0);
        putUnknownFunc(0x0114, 2);
        putUnknownFunc(0x0115, 1);
        putUnknownFunc(0x0116, 1);
        putUnknownFunc(0x0117, 1);
        putUnknownFunc(0x0119, 1);
        putUnknownFunc(0x011A, 3);
        putUnknownFunc(0x011B, 2);
        putUnknownFunc(0x011C, 1);
        putUnknownFunc(0x011D, 2);
        putUnknownFunc(0x011F, 3);
        putUnknownFunc(0x0120, 3);
        putFuncWithIdx(0x0121, new ScriptFunc("movementStickTilt?", "int", null, p("axis", "int")));
        putUnknownFunc(0x0122, 1);
        putUnknownFunc(0x0126, 3);
        putUnknownFunc(0x0127, 1);
        putUnknownFunc(0x0128, 2);
        putUnknownFunc(0x0129, 4);
        putUnknownFunc(0x012A, 2);
        putUnknownFunc(0x012B, 1);
        putUnknownFunc(0x012D, 1);
        putUnknownFunc(0x012E, 2);
        putUnknownFunc(0x0130, 2);
        putUnknownFunc(0x0132, 2);
        putUnknownFunc(0x0133, 2);
        putFuncWithIdx(0x0134, new ScriptFunc(p("model")));
        putFuncWithIdx(0x0135, new ScriptFunc("PlayerTotalGil", "int", null, false));
        putUnknownFunc(0x0136, 1);
        putFuncWithIdx(0x0137, new ScriptFunc("makeGilPayment", "bool", null, p("amount", "int")));
        putUnknownFunc(0x0138, 1);
        putUnknownFunc(0x0139, 8);
        putFuncWithIdx(0x0139, new ScriptFunc("requestNumericInput?", "int", null, p(1), p(2), p(3), p(4), p(5), p("x?", "int"), p("y?", "int"), p("alignment?", "textAlignment")));
        putFuncWithIdx(0x013B, new ScriptFunc("displayFieldChoice", "int", null, p("boxIndex?", "int"), p("string"), p(3), p(4), p("x?", "int"), p("y?", "int"), p("alignment?", "textAlignment")));
        putUnknownFunc(0x013D, 1);
        putUnknownFunc(0x013E, 1);
        putUnknownFunc(0x013F, 2);
        putUnknownFunc(0x0140, 6);
        putUnknownFunc(0x0141, 3);
        putUnknownFunc(0x0142, 2); // Corrected from 3, must be 2 due to bltz0200.ebp
        putUnknownFunc(0x0143, 1);
        putUnknownFunc(0x0144, 1);
        putUnknownFunc(0x0145, 2);
        putUnknownFunc(0x0146, 1);
        putUnknownFunc(0x0148, 2);
        putUnknownFunc(0x0149, 1);
        putUnknownFunc(0x014A, 3);
        putUnknownFunc(0x014D, 0);
        putUnknownFunc(0x014E, 3);
        putUnknownFunc(0x014F, 3);
        putUnknownFunc(0x0151, 1);
        putUnknownFunc(0x0154, 0);
        putUnknownFunc(0x0155, 1);
        putUnknownFunc(0x0156, 0);
        putUnknownFunc(0x0157, 1);
        putUnknownFunc(0x0158, 1);
        putUnknownFunc(0x0159, 2);
        putFuncWithIdx(0x015B, new ScriptFunc("obtainTreasure", "unknown", null, p("textboxIndex", "int"), p("treasure")));
        putUnknownFunc(0x015D, 1);
        putUnknownFunc(0x015E, 1);
        putUnknownFunc(0x015F, 1);
        putFuncWithIdx(0x0160, new ScriptFunc("hasKeyItem", "bool", null, p("keyItem")));
        putUnknownFunc(0x0161, 1);
        putUnknownFunc(0x0166, 1);
        putUnknownFunc(0x0167, 0);
        putUnknownFunc(0x016A, 2); // maca0200.ebp
        putUnknownFunc(0x016B, 3);
        putUnknownFunc(0x016C, 0);
        putFuncWithIdx(0x016D, new ScriptFunc(p("bgm")));
        putUnknownFunc(0x016E, 2);
        putUnknownFunc(0x016F, 1);
        putFuncWithIdx(0x0171, new ScriptFunc("restorePartyMemberHP?", "unknown", null, p("actor")));
        putFuncWithIdx(0x0172, new ScriptFunc("restorePartyMemberMP?", "unknown", null, p("actor")));
        putUnknownFunc(0x0174, 0);
        putUnknownFunc(0x0177, 1);
        putUnknownFunc(0x0179, 1);
        putUnknownFunc(0x017A, 1);
        putUnknownFunc(0x017B, 1);
        putUnknownFunc(0x017C, 1);
        putFuncWithIdx(0x017E, new ScriptFunc("playBgmInclBattle?", "unknown", null, p("bgm"), p(2)));
        putUnknownFunc(0x017F, 1);
        putUnknownFunc(0x0180, 2);
        putUnknownFunc(0x0181, 0);
        putUnknownFunc(0x0184, 1);
        putUnknownFunc(0x0185, 2);
        putUnknownFunc(0x0188, 1);
        putUnknownFunc(0x0189, 1);
        putUnknownFunc(0x018A, 1);
        putUnknownFunc(0x018B, 1);
        putUnknownFunc(0x018F, 2);
        putUnknownFunc(0x0192, 1);
        putUnknownFunc(0x0193, 1);
        putUnknownFunc(0x0194, 1);
        putUnknownFunc(0x0195, 0);
        putUnknownFunc(0x0196, 1);
        putUnknownFunc(0x0197, 1);
        putFuncWithIdx(0x0198, new ScriptFunc("enableVisualEffectIndex", "unknown", null, p("levelPartIndex?", "int"), p("effectIndex?", "int"), p("runOnce", "bool")));
        putFuncWithIdx(0x0199, new ScriptFunc("enableOwnVisualEffectIndex", "unknown", null, p("effectIndex", "int"), p("runOnce", "bool")));
        putUnknownFunc(0x019C, 0);
        putUnknownFunc(0x019D, 1);
        putUnknownFunc(0x019E, 0);
        putUnknownFunc(0x019F, 1);
        putUnknownFunc(0x01A0, 3);
        putUnknownFunc(0x01A4, 2);
        putUnknownFunc(0x01A5, 2);
        putUnknownFunc(0x01A6, 0);
        putFuncWithIdx(0x01A7, new ScriptFunc("obtainTreasureSilently", "unknown", null, p("treasure")));
        putUnknownFunc(0x01A8, 1);
        putUnknownFunc(0x01AB, 0);
        putUnknownFunc(0x01AC, 1);
        putUnknownFunc(0x01AD, 1);
        putUnknownFunc(0x01AF, 2);
        putUnknownFunc(0x01B0, 2);
        putUnknownFunc(0x01B1, 0);
        putFuncWithIdx(0x01B2, new ScriptFunc("getItemCount", "int", null, p("item", "move")));
        putUnknownFunc(0x01B5, 0);
        putUnknownFunc(0x01B6, 0);
        putUnknownFunc(0x01B7, 1);
        putUnknownFunc(0x01B8, 0);
        putUnknownFunc(0x01BA, 2);
        putUnknownFunc(0x01BB, 0);
        putUnknownFunc(0x01BC, 1);
        putUnknownFunc(0x01BD, 1);
        putUnknownFunc(0x01BF, 0);
        putUnknownFunc(0x01C0, 2);
        putUnknownFunc(0x01C2, 0);
        putUnknownFunc(0x01C3, 1);
        putUnknownFunc(0x01C4, 1);
        putUnknownFunc(0x01C5, 2);
        putUnknownFunc(0x01C6, 0);
        putFuncWithIdx(0x01C8, new ScriptFunc("disableOwnVisualEffect", "unknown", null, p("effectType", "int"))); // Never used by the game
        putFuncWithIdx(0x01C9, new ScriptFunc("enableVisualEffect", "unknown", null, p("effectType?", "int"), p("levelPartIndex?", "int")));
        putUnknownFunc(0x01CA, 0);
        putUnknownFunc(0x01CC, 0);
        putUnknownFunc(0x01CE, 0);
        putUnknownFunc(0x01CF, 0);
        putUnknownFunc(0x01D0, 0);
        putUnknownFunc(0x01D1, 1);
        putFuncWithIdx(0x01D2, new ScriptFunc("enteredAirshipPasswordEquals", "bool", null, p("string")));
        putUnknownFunc(0x01D4, 2);
        putUnknownFunc(0x01D9, 0);
        putUnknownFunc(0x01DA, 4);
        putUnknownFunc(0x01DC, 0);
        putUnknownFunc(0x01DE, 0);
        putUnknownFunc(0x01E0, 1);
        putUnknownFunc(0x01E2, 0);
        putUnknownFunc(0x01E3, 0);
        putUnknownFunc(0x01E4, 4);
        putUnknownFunc(0x01E5, 3);
        putUnknownFunc(0x01E6, 3);
        putUnknownFunc(0x01E7, 2);
        putUnknownFunc(0x01E9, 2);
        putUnknownFunc(0x01EB, 1);
        putUnknownFunc(0x01EE, 0);
        putUnknownFunc(0x01F0, 1);
        putUnknownFunc(0x01F2, 0);
        putUnknownFunc(0x01F3, 3);
        putUnknownFunc(0x01F4, 2);
        putUnknownFunc(0x01F8, 2);
        putUnknownFunc(0x01F9, 1);
        putUnknownFunc(0x01FA, 0);
        putUnknownFunc(0x01FB, 0);
        putFuncWithIdx(0x01FC, new ScriptFunc("teachAbilityToPartyMember", "unknown", null, p("actor"), p("charMove")));
        putUnknownFunc(0x0200, 1);
        putUnknownFunc(0x0201, 0);
        putUnknownFunc(0x0202, 1);
        putUnknownFunc(0x0203, 1);
        putUnknownFunc(0x0204, 1);
        putUnknownFunc(0x0205, 0);
        putUnknownFunc(0x0206, 0);
        putUnknownFunc(0x0207, 0);
        putUnknownFunc(0x0209, 0);
        putUnknownFunc(0x020A, 0);
        putUnknownFunc(0x020B, 0);
        putUnknownFunc(0x020D, 1);
        putUnknownFunc(0x020F, 1);
        putFuncWithIdx(0x0210, new ScriptFunc("setMonsterArenaUnlocked", "unknown", null, p("monsterArenaUnlock")));
        putUnknownFunc(0x0212, 2);
        putUnknownFunc(0x0213, 1);
        putFuncWithIdx(0x0215, new ScriptFunc("grantCelestialUpgrade", "unknown", null, p("actor"), p("level", "int")));
        putUnknownFunc(0x0216, 3);
        putUnknownFunc(0x0217, 0);
        putUnknownFunc(0x021A, 2);
        putUnknownFunc(0x021B, 2);
        putUnknownFunc(0x021D, 0);
        putUnknownFunc(0x021E, 0);
        putUnknownFunc(0x0220, 1);
        putUnknownFunc(0x0221, 1);
        putFuncWithIdx(0x0225, new ScriptFunc("setShopPrices", "unknown", null, p("percentage", "int")));
        putUnknownFunc(0x0226, 1);
        putUnknownFunc(0x0229, 0);
        putUnknownFunc(0x022D, 1);
        putUnknownFunc(0x022E, 4);
        putUnknownFunc(0x022F, 2);
        putUnknownFunc(0x0231, 1);
        putUnknownFunc(0x0234, 0);
        putUnknownFunc(0x0235, 0);
        putUnknownFunc(0x0236, 1);
        putUnknownFunc(0x0237, 4);
        putUnknownFunc(0x0239, 1);
        putUnknownFunc(0x023A, 1);
        putUnknownFunc(0x023B, 1); // These two could add up to 3 differently...
        putUnknownFunc(0x023C, 2); // But this seems most reasonable. Check nagi0700
        putUnknownFunc(0x023D, 0);
        putUnknownFunc(0x023F, 1);
        putUnknownFunc(0x0240, 2);
        putUnknownFunc(0x0241, 1);
        putUnknownFunc(0x0242, 0);
        putUnknownFunc(0x0243, 0);
        putUnknownFunc(0x0244, 0);
        putUnknownFunc(0x0245, 0);
        putUnknownFunc(0x024A, 1);
        putUnknownFunc(0x024B, 2);
        putUnknownFunc(0x024C, 0);
        putUnknownFunc(0x024D, 1);
        putUnknownFunc(0x0251, 1);
        putUnknownFunc(0x0253, 0);
        putFuncWithIdx(0x0254, new ScriptFunc("setSphereGrid", "unknown", null, p("sphereGrid")));
        putUnknownFunc(0x0255, 0);
        putUnknownFunc(0x0256, 1);
        putUnknownFunc(0x0257, 1);
        putUnknownFunc(0x0259, 2);
        putUnknownFunc(0x025B, 1);
        putUnknownFunc(0x025C, 0);
        putUnknownFunc(0x025D, 1);
        putUnknownFunc(0x025E, 1);
        putUnknownFunc(0x025F, 2);
        putUnknownFunc(0x0260, 1);
        putUnknownFunc(0x0261, 1);
        putUnknownFunc(0x0262, 0);
        putUnknownFunc(0x0263, 0);
        putUnknownFunc(0x0264, 1);
        putUnknownFunc(0x0265, 0);
        putUnknownFunc(0x0266, 0);
        putUnknownFunc(0x0267, 7);
        putUnknownFunc(0x1000, 4);
        putFuncWithIdx(0x1001, new ScriptFunc("sin", "float", null, p("float")));
        putFuncWithIdx(0x1002, new ScriptFunc("cos", "float", null, p("float")));
        putUnknownFunc(0x1005, 2);
        putFuncWithIdx(0x1006, new ScriptFunc("sqrt", "float", null, p("float")));
        putUnknownFunc(0x100A, 1);
        putUnknownFunc(0x1013, 1); // This is a guess, could also be 0 if 0x1001 and 0x1002 are 2 instead of 1
        putUnknownFunc(0x1015, 6);
        putUnknownFunc(0x1019, 1);
        putUnknownFunc(0x101A, 4);
        putUnknownFunc(0x101B, 6);
        putUnknownFunc(0x101C, 2);
        putUnknownFunc(0x4001, 1);
        putUnknownFunc(0x4003, 4);
        putUnknownFunc(0x4004, 1);
        putUnknownFunc(0x4005, 1);
        putUnknownFunc(0x4006, 1);
        putUnknownFunc(0x4007, 1);
        putUnknownFunc(0x4008, 4);
        putUnknownFunc(0x4009, 4);
        putUnknownFunc(0x400A, 1);
        putUnknownFunc(0x400B, 0);
        putUnknownFunc(0x400C, 0);
        putUnknownFunc(0x400D, 0);
        putUnknownFunc(0x400E, 1);
        putUnknownFunc(0x400F, 1);
        putUnknownFunc(0x4013, 6);
        putUnknownFunc(0x4014, 1);
        putUnknownFunc(0x4015, 2);
        putUnknownFunc(0x4016, 2);
        putUnknownFunc(0x4017, 2);
        putUnknownFunc(0x4019, 1);
        putUnknownFunc(0x401A, 2);
        putUnknownFunc(0x401B, 1);
        putUnknownFunc(0x401C, 1);
        putFuncWithIdx(0x401D, new ScriptFunc("showModularMenu", "unknown", null, p("menu")));
        putUnknownFunc(0x401F, 0);
        putUnknownFunc(0x4020, 0);
        putUnknownFunc(0x4022, 1);
        putUnknownFunc(0x4023, 1);
        putUnknownFunc(0x4024, 0);
        putUnknownFunc(0x4025, 9);
        putUnknownFunc(0x402A, 2);
        putUnknownFunc(0x4034, 1);
        putUnknownFunc(0x4036, 3);
        putUnknownFunc(0x4039, 4);
        putUnknownFunc(0x403A, 1);
        putUnknownFunc(0x403B, 2);
        putUnknownFunc(0x403C, 1);
        putUnknownFunc(0x403E, 2);
        putUnknownFunc(0x403F, 0);
        putUnknownFunc(0x4040, 1);
        putUnknownFunc(0x4043, 2);
        putUnknownFunc(0x4044, 3);
        putUnknownFunc(0x4045, 1);
        putUnknownFunc(0x4046, 1);
        putUnknownFunc(0x5000, 1); // Why was this 0?
        putUnknownFunc(0x5001, 1); // noclip: load motion group
        putUnknownFunc(0x5003, 0);
        putUnknownFunc(0x5005, 0);
        putUnknownFunc(0x5006, 1);
        putUnknownFunc(0x5007, 4);
        putUnknownFunc(0x5008, 1);
        putUnknownFunc(0x5009, 1);
        putUnknownFunc(0x500B, 1);
        putUnknownFunc(0x500C, 1);
        putUnknownFunc(0x500D, 1);
        putUnknownFunc(0x500E, 1);
        putUnknownFunc(0x500F, 1);
        putFuncWithIdx(0x5010, new ScriptFunc(p("model"), p(2)));
        putUnknownFunc(0x5013, 1);
        putUnknownFunc(0x5014, 2);
        putUnknownFunc(0x5015, 4);
        putUnknownFunc(0x5016, 3);
        putUnknownFunc(0x5017, 1);
        putUnknownFunc(0x5018, 1);
        putUnknownFunc(0x5019, 5);
        putFuncWithIdx(0x501A, new ScriptFunc(p("motion"), p(2), p(3), p(4), p(5)));
        putFuncWithIdx(0x501B, new ScriptFunc("playCharMotion", "unknown", null, p("motion")));
        putUnknownFunc(0x501E, 0);
        putUnknownFunc(0x501F, 0);
        putUnknownFunc(0x5020, 0);
        putUnknownFunc(0x5021, 1);
        putUnknownFunc(0x5022, 1);
        putFuncWithIdx(0x5025, new ScriptFunc(p(1), p("motion")));
        putUnknownFunc(0x5026, 5);
        putUnknownFunc(0x5028, 1);
        putUnknownFunc(0x5029, 1);
        putUnknownFunc(0x502A, 1);
        putUnknownFunc(0x502C, 2);
        putUnknownFunc(0x502D, 2);
        putUnknownFunc(0x5032, 0);
        putUnknownFunc(0x5033, 2);
        putUnknownFunc(0x5034, 1);
        putUnknownFunc(0x5035, 0);
        putUnknownFunc(0x5036, 5);
        putUnknownFunc(0x5037, 4);
        putUnknownFunc(0x5039, 1);
        putUnknownFunc(0x503A, 1);
        putUnknownFunc(0x503B, 2);
        putUnknownFunc(0x503C, 1);
        putUnknownFunc(0x503D, 1);
        putUnknownFunc(0x503E, 2);
        putUnknownFunc(0x503F, 1);
        putFuncWithIdx(0x5040, new ScriptFunc(p("motion")));
        putFuncWithIdx(0x5042, new ScriptFunc(p("motion"), p(2), p(3), p(4), p(5)));
        putUnknownFunc(0x5044, 6);
        putUnknownFunc(0x5046, 6);
        putUnknownFunc(0x5047, 2);
        putUnknownFunc(0x5048, 2);
        putUnknownFunc(0x5049, 1);
        putUnknownFunc(0x504A, 1);
        putUnknownFunc(0x504B, 1);
        putUnknownFunc(0x504C, 2);
        putUnknownFunc(0x504D, 1);
        putFuncWithIdx(0x504E, new ScriptFunc(p("model")));
        putFuncWithIdx(0x504F, new ScriptFunc(p("model")));
        putUnknownFunc(0x5050, 2);
        putUnknownFunc(0x5051, 0);
        putUnknownFunc(0x5052, 5);
        putUnknownFunc(0x5054, 2);
        putUnknownFunc(0x5056, 1);
        putUnknownFunc(0x5057, 2);
        putUnknownFunc(0x5058, 1);
        putUnknownFunc(0x505A, 2);
        putUnknownFunc(0x505C, 1);
        putUnknownFunc(0x505D, 0);
        putUnknownFunc(0x505E, 0);
        putUnknownFunc(0x505F, 1);
        putUnknownFunc(0x5060, 1);
        putFuncWithIdx(0x5061, new ScriptFunc(p("model"), p(2)));
        putFuncWithIdx(0x5063, new ScriptFunc(p("model"), p(2)));
        putUnknownFunc(0x5065, 1);
        putUnknownFunc(0x5066, 1);
        putUnknownFunc(0x5067, 1);
        putUnknownFunc(0x5068, 0);
        putUnknownFunc(0x5069, 1);
        putUnknownFunc(0x506A, 1);
        putUnknownFunc(0x506D, 2);
        putUnknownFunc(0x506E, 1);
        putUnknownFunc(0x506F, 1);
        putUnknownFunc(0x5071, 1);
        putUnknownFunc(0x5072, 0);
        putUnknownFunc(0x5073, 1);
        putUnknownFunc(0x5075, 1);
        putUnknownFunc(0x5076, 1);
        putUnknownFunc(0x5078, 2);
        putUnknownFunc(0x5079, 1);
        putUnknownFunc(0x507A, 1);
        putUnknownFunc(0x507B, 3);
        putUnknownFunc(0x507C, 0);
        putUnknownFunc(0x507D, 2);
        putUnknownFunc(0x507E, 2);
        putUnknownFunc(0x5080, 1);
        putUnknownFunc(0x5081, 1);
        putUnknownFunc(0x5082, 1);
        putUnknownFunc(0x5083, 1);
        putUnknownFunc(0x5084, 1);
        putUnknownFunc(0x5085, 1);
        putUnknownFunc(0x5086, 0);
        putUnknownFunc(0x5087, 0);
        putUnknownFunc(0x5088, 2);
        putUnknownFunc(0x5089, 5);
        putUnknownFunc(0x508B, 5);
        putUnknownFunc(0x508D, 1);
        putUnknownFunc(0x508E, 1);
        putUnknownFunc(0x508F, 1);
        putUnknownFunc(0x5090, 1);
        putUnknownFunc(0x6000, "camSleep", 1);
        putUnknownFunc(0x6001, "camWakeUp", 1);
        putUnknownFunc(0x6002, "camSetPos", 3);
        putUnknownFunc(0x6003, "camGetPos", 3);
        putUnknownFunc(0x6004, "camSetPolar", 3);
        putUnknownFunc(0x6005, "camSetPolarOffset", 3);
        putUnknownFunc(0x6006, "camSetHypot", 6);
        putUnknownFunc(0x6007, "camSetHypot2", 6);
        putUnknownFunc(0x6008, "camSetHypot3", 6);
        putUnknownFunc(0x6009, "camSetAct", 3);
        putUnknownFunc(0x600A, "camSetFilter", 5);
        putUnknownFunc(0x600B, "camSetFilter2", 5);
        putUnknownFunc(0x600C, "camSetFilterY", 3);
        putUnknownFunc(0x600D, "camSetFilterY2", 3);
        putUnknownFunc(0x600E, "camSleepFilter", 1);
        putUnknownFunc(0x600F, "camResetFilter", 0);
        putUnknownFunc(0x6010, "camMove", 1);
        putUnknownFunc(0x6011, "camMovePolar", 1);
        putUnknownFunc(0x6012, "camMoveCos", 1);
        putUnknownFunc(0x6013, "camMovePolarCos", 1);
        putUnknownFunc(0x6014, "camMoveAcc", 4);
        putUnknownFunc(0x6015, "camMovePolarAcc", 4);
        putUnknownFunc(0x6016, "camResetMove", 0);
        putUnknownFunc(0x6017, "camSetInertia", 4);
        putUnknownFunc(0x6018, "camSetDirVector", 3);
        putUnknownFunc(0x6019, "camResetDirVector", 0);
        putUnknownFunc(0x601A, "camWait", 0);
        putUnknownFunc(0x601B, "camCheck", 0);
        putUnknownFunc(0x601C, "camSetDataPoint", 2);
        putUnknownFunc(0x601D, "camSetDataPointHypot", 4);
        putUnknownFunc(0x601E, "camSetDataPoint2", 2);
        putUnknownFunc(0x601F, "camSetDataPointHypot2", 4);
        putUnknownFunc(0x6020, "refSetPos", 3);
        putUnknownFunc(0x6021, "refGetPos", 3);
        putUnknownFunc(0x6022, "refSetPolar", 3);
        putUnknownFunc(0x6023, "refSetPolarOffset", 3);
        putUnknownFunc(0x6024, "refSetHypot", 6);
        putUnknownFunc(0x6025, "refSetHypot2", 6);
        putUnknownFunc(0x6026, "refSetHypot3", 6);
        putUnknownFunc(0x6027, "refSetAct", 3);
        putUnknownFunc(0x6028, "refSetFilter", 5);
        putUnknownFunc(0x6029, "refSetFilter2", 5);
        putUnknownFunc(0x602A, "refSetFilterY", 3);
        putUnknownFunc(0x602B, "refSetFilterY2", 3);
        putUnknownFunc(0x602C, "refSleepFilter", 1);
        putUnknownFunc(0x602D, "refResetFilter", 0);
        putUnknownFunc(0x602E, "refMove", 1);
        putUnknownFunc(0x602F, "refMovePolar", 1);
        putUnknownFunc(0x6030, "refMoveCos", 1);
        putUnknownFunc(0x6031, "refMovePolarCos", 1);
        putUnknownFunc(0x6032, "refMoveAcc", 4);
        putUnknownFunc(0x6033, "refMovePolarAcc", 4);
        putUnknownFunc(0x6034, "refResetMove", 0);
        putUnknownFunc(0x6035, "refSetInertia", 4);
        putUnknownFunc(0x6036, "refSetDirVector", 4);
        putUnknownFunc(0x6037, "refResetDirVector", 0);
        putUnknownFunc(0x6038, "refWait", 0);
        putUnknownFunc(0x6039, "refCheck", 0);
        putUnknownFunc(0x603A, "camSetRoll", 1);
        putUnknownFunc(0x603B, "camSetScrDpt", 1);
        putUnknownFunc(0x603C, "camSetAct2", 4);
        putUnknownFunc(0x603D, "refSetAct2", 4);
        putUnknownFunc(0x603E, "camSetBtl", 3);
        putUnknownFunc(0x603F, "refSetBtl", 3);
        putUnknownFunc(0x6040, "camSetBtlPolar", 6);
        putUnknownFunc(0x6041, "refSetBtlPolar", 6);
        putUnknownFunc(0x6042, "refMoveStat", 1);
        putUnknownFunc(0x6043, "camMoveStat", 1);
        putUnknownFunc(0x6044, "camSetBtlPolar2", 6);
        putUnknownFunc(0x6045, "refSetBtlPolar2", 6);
        putUnknownFunc(0x6046, "camSetSpline", 4);
        putUnknownFunc(0x6047, "refSetSpline", 4);
        putUnknownFunc(0x6048, "camStartSpline", 0);
        putUnknownFunc(0x6049, "camRegSpline", 0);
        putUnknownFunc(0x604A, "refStartSpline", 0);
        putUnknownFunc(0x604B, "refRegSpline", 0);
        putUnknownFunc(0x604C, "camSetChrPolar", 6);
        putUnknownFunc(0x604D, "camSetChrPolar2", 6);
        putUnknownFunc(0x604E, "camScrSet", 6);
        putUnknownFunc(0x604F, "camScrOff", 1);
        putUnknownFunc(0x6050, "camDrawSet", 5);
        putUnknownFunc(0x6051, "camDrawLink", 2);
        putUnknownFunc(0x6052, "camScrLink", 2);
        putUnknownFunc(0x6053, "camScrMove", 2);
        putUnknownFunc(0x6054, "camScrMoveCos", 2);
        putUnknownFunc(0x6055, "camScrMoveAcc", 4);
        putUnknownFunc(0x6056, "camDrawMove", 2);
        putUnknownFunc(0x6057, "camDrawMoveCos", 2);
        putUnknownFunc(0x6058, "camDrawMoveAcc", 4);
        putUnknownFunc(0x6059, "refSetSplineFilter", 2);
        putUnknownFunc(0x605A, "refSetSplineFilter2", 3);
        putUnknownFunc(0x605B, "camSetSpline2", 2);
        putUnknownFunc(0x605C, "refSetShake", 5);
        putUnknownFunc(0x605D, "camSetShake", 5);
        putUnknownFunc(0x605E, "camSetScreenShake", 6);
        putUnknownFunc(0x605F, "refResetShake", 0);
        putUnknownFunc(0x6060, "camResetShake", 0);
        putUnknownFunc(0x6061, "camResetScreenShake", 1);
        putUnknownFunc(0x6062, "refWaitShake", 0);
        putUnknownFunc(0x6063, "camWaitShake", 0);
        putUnknownFunc(0x6064, "camWaitScreenShake", 1);
        putUnknownFunc(0x6065, "camPriority", 1);
        putUnknownFunc(0x6066, "refSetShakeB", 5);
        putUnknownFunc(0x6067, "camSetShakeB", 5);
        putUnknownFunc(0x6068, "camSetScreenShakeB", 6);
        putUnknownFunc(0x6069, "refSetShake2", 5);
        putUnknownFunc(0x606A, "camSetShake2", 5);
        putUnknownFunc(0x606B, "camSetScreenShake2", 6);
        putUnknownFunc(0x606C, "refSetShake2B", 5);
        putUnknownFunc(0x606D, "camSetShake2B", 5);
        putUnknownFunc(0x606E, "camSetScreenShake2B", 6);
        putUnknownFunc(0x606F, "refSetShake3", 5);
        putUnknownFunc(0x6070, "camSetShake3", 5);
        putUnknownFunc(0x6071, "camSetScreenShake3", 6);
        putUnknownFunc(0x6072, "refSetShake3B", 5);
        putUnknownFunc(0x6073, "camSetShake3B", 5);
        putUnknownFunc(0x6074, "camSetScreenShake3B", 6);
        putUnknownFunc(0x6075, "camScrSetCam", 2);
        putUnknownFunc(0x6076, "camFreeBattle", 0);
        putUnknownFunc(0x6077, "camGetRoll", "float", 0);
        putUnknownFunc(0x6078, "camGetScrDpt", "float", 0);
        putUnknownFunc(0x6079, "camScrResetMove", 1);
        putUnknownFunc(0x607A, "camDrawResetMove", 1);
        putUnknownFunc(0x607B, "camScrWait", 1);
        putUnknownFunc(0x607C, "camDrawWait", 1);
        putUnknownFunc(0x607D, "camBlur", 1);
        putUnknownFunc(0x607E, "camFocus", 1);
        putUnknownFunc(0x607F, "camSetFocus", 2);
        putUnknownFunc(0x6080, "camRand", 1);
        putUnknownFunc(0x6081, "refSetShake4", 5);
        putUnknownFunc(0x6082, "camSetShake4", 5);
        putUnknownFunc(0x6083, "refSetShake5", 5);
        putUnknownFunc(0x6084, "camSetShake5", 5);
        putUnknownFunc(0x6085, "camGetRealPos", 3);
        putUnknownFunc(0x6086, "refGetRealPos", 3);
        putUnknownFunc(0x6087, "refReset", 0);
        putUnknownFunc(0x6088, "camReset", 0);
        putUnknownFunc(0x7000, "btlTerminateAction", 0);
        putUnknownFunc(0x7001, "btlSetRandPosFlag", 1);
        putFuncWithIdx(0x7002, new ScriptFunc("launchBattle", "unknown", "btlExe", p("encounter"), p("transition?", "battleTransition")));
        putUnknownFunc(0x7003, "btlDirTarget", 2);
        putUnknownFunc(0x7004, "btlSetDirRate", 1);
        putFuncWithIdx(0x7005, new ScriptFunc("isWater?", "int", "btlGetWater", false));
        putUnknownFunc(0x7006, "btlDirBasic", 2);
        putFuncWithIdx(0x7007, new ScriptFunc("startMotion?", "unknown", "btlSetMotion", p("int")));
        putFuncWithIdx(0x7008, new ScriptFunc("awaitMotion?", "unknown", "btlWaitMotion", true));
        putFuncWithIdx(0x7009, new ScriptFunc("setGravity?", "unknown", "btlSetGravity", p("bool")));
        putFuncWithIdx(0x700A, new ScriptFunc("setHeight?", "unknown", "btlSetHeight", p("int"), p("float")));
        putFuncWithIdx(0x700B, new ScriptFunc("performMove", "bool", "btlSetDirectCommand", p("target", "actor"), p("move")));
        putUnknownFunc(0x700C, "btlMove", 8);
        putUnknownFunc(0x700D, "btlDirPos", 2);
        putUnknownFunc(0x700E, "btlSetDamage", 1);
        putFuncWithIdx(0x700F, new ScriptFuncAccessor("readActorProperty", "actor", "btlGetStat", null, "actorProperty"));
        putFuncWithIdx(0x7010, new ScriptFunc("defineActorSubset", "actor", "btlSearchChr", p("group", "actor"), p("property", "actorProperty"), p("unknown"), p("selector")));
        putUnknownFunc(0x7011, "btlCameraMode", 1);
        putUnknownFunc(0x7012, "btlTerminateEffect", 0);
        putUnknownFunc(0x7013, "btlChrSp", 1);
        putFuncWithIdx(0x7014, new ScriptFunc("chosenMove?", "move", "btlGetComNum", false));
        putFuncWithIdx(0x7015, new ScriptFunc("print?", "unknown", "btlPrint", p("int")));
        putFuncWithIdx(0x7016, new ScriptFunc("stopMotion?", "unknown", "btlTerminateMotion", p("int")));
        putUnknownFunc(0x7017, "btlSetNormalEffect", 2);
        putFuncWithIdx(0x7018, new ScriptFuncAccessor("writeActorProperty", "actor", "btlSetStat", "=", "actorProperty"));
        putFuncWithIdx(0x7019, new ScriptFunc("usedMove", "move", "btlGetReCom", false));
        putFuncWithIdx(0x701A, new ScriptFuncAccessor("readMoveProperty", "move", "btlGetComInfo", null, "moveProperty"));
        putFuncWithIdx(0x701B, new ScriptFunc("overrideAttemptedAction", "unknown", "btlChangeReCom", p("target", "actor"), p("move")));
        putUnknownFunc(0x701C, "btlSetMotionLevel", 1);
        putUnknownFunc(0x701D, "btlGetMotionLevel", 0);
        putFuncWithIdx(0x701E, new ScriptFunc("countActorsIn", "int", "btlCountChr", p("within", "actor"), p("actor")));
        putUnknownFunc(0x701F, "btlChgWaitMotion", 1);
        putUnknownFunc(0x7020, "btlCheckStartEffect", 0);
        putFuncWithIdx(0x7021, new ScriptFunc("dereferenceCharacter", "actor", "btlGetChrNum", p("actor")));
        putFuncWithIdx(0x7022, new ScriptFunc("SetAmbushState", "unknown", "btlSetFirstAttack", p("ambushState")));
        putUnknownFunc(0x7023, "btlDistTarget", 1);
        putFuncWithIdx(0x7024, new ScriptFunc("CurrentEncounterIndex", "encounter", "btlGetBtlScene", false));
        putFuncWithIdx(0x7025, new ScriptFunc("defineActorSubset2?", "actor", "btlSearchChr2", p("group", "actor"), p("property", "actorProperty"), p("unknown"), p("selector")));
        putUnknownFunc(0x7026, "btlSetWeak", 1);
        putUnknownFunc(0x7027, "btlGetWeak", 0);
        putFuncWithIdx(0x7028, new ScriptFunc("scaleOwnSize", "unknown", "btlSetScale", p("x?", "float"), p("y?", "float"), p("z?", "float")));
        putFuncWithIdx(0x7029, new ScriptFuncAccessor("setSelfFloating", null, "btlSetFly", "=", p("floating", "bool")));
        putUnknownFunc(0x702A, "btlCheckBtlPos", 0);
        putUnknownFunc(0x702B, "btlCheckMotion", 0);
        putUnknownFunc(0x702C, "btlSetHoming", 9);
        putUnknownFunc(0x702D, "btlResetMove", 0);
        putUnknownFunc(0x702E, "btlMoveTargetDist", "float", 1);
        putUnknownFunc(0x702F, "btlOut", 1);
        putUnknownFunc(0x7030, "btlGetMoveFlag", 0);
        putUnknownFunc(0x7031, "btlStartMotion", 0);
        putFuncWithIdx(0x7032, new ScriptFuncAccessor("setActorFacingAngle", "actor", "btlSetBtlPosDir", "=", p("facingAngle", "float")));
        putUnknownFunc(0x7033, "btlSetEnMapID", 1);
        putFuncWithIdx(0x7034, new ScriptFunc("endBattle", "unknown", "btlComplete", p("battleEndType")));
        putFuncWithIdx(0x7035, new ScriptFunc("BattleEndType", "battleEndType", "btlGetCompInfo", false));
        putUnknownFunc(0x7036, "btlSetTrans", 3);
        putFuncWithIdx(0x7037, new ScriptFunc("addMove", "unknown", "btlAddCom", p("actor"), p("move")));
        putFuncWithIdx(0x7038, new ScriptFunc("removeMove", "unknown", "btlDelCom", p("actor"), p("move")));
        putUnknownFunc(0x7039, "btlTerminateDeath", 0);
        putUnknownFunc(0x703A, "btlSetSpeed", 1);
        putFuncWithIdx(0x703B, new ScriptFunc("setMoveDisabled", "unknown", "btlSetCommandUse", p("actor"), p("move"), p("disabled", "bool")));
        putFuncWithIdx(0x703C, new ScriptFunc("runBattleScriptA", "unknown", "btlOff", p("index", "int")));
        putUnknownFunc(0x703D, "btlOn", 0);
        putUnknownFunc(0x703E, "btlWait", 0);
        putUnknownFunc(0x703F, "camReq", 2);
        putUnknownFunc(0x7040, "btlMagicStart", 1);
        putUnknownFunc(0x7041, "btlMagicEnd", 0);
        putFuncWithIdx(0x7042, new ScriptFunc("displayBattleString", "unknown", "btlmes", p("boxIndex", "int"), p("string"), p("x?", "int"), p("y?", "int"), p("p5", "unknown")));
        putFuncWithIdx(0x7043, new ScriptFunc("closeTextOnConfirm", "unknown", "btlmeswait", p("boxIndex", "int")));
        putFuncWithIdx(0x7044, new ScriptFunc("closeTextImmediately", "unknown", "btlmesclose", p("boxIndex", "int")));
        putUnknownFunc(0x7045, "btlDistTargetFrame", 1);
        putUnknownFunc(0x7046, "btlSplineStart", 1);
        putUnknownFunc(0x7047, "btlSplineRegist", 2);
        putUnknownFunc(0x7048, "btlSplineRegistPos", 4);
        putUnknownFunc(0x7049, "btlSplineMove", 4);
        putUnknownFunc(0x704A, "btlCheckMove", 1);
        putUnknownFunc(0x704B, "btlReqMotion", 3);
        putUnknownFunc(0x704C, "btlWaitReqMotion", 1);
        putUnknownFunc(0x704D, "btlSetDeathLevel", 1);
        putUnknownFunc(0x704E, "btlSetDeathPattern", 1);
        putUnknownFunc(0x704F, "btlSetEventChrFlag", 2);
        putFuncWithIdx(0x7050, new ScriptFunc("revive/reinitialize", "unknown", "btlResetParam", p("actor")));
        putUnknownFunc(0x7051, "btlWaitNormalEffect", 0);
        putFuncWithIdx(0x7052, new ScriptFunc("attachActor", "unknown", "btlChrLink", p( "actor"), p( "host","actor"), p( "attachmentPoint","int")));
        putUnknownFunc(0x7053, "btlMoveJump", 9);
        putUnknownFunc(0x7054, "btlSetChrPosElem", 3);
        putUnknownFunc(0x7055, "btlSetBodyHit", 1);
        putUnknownFunc(0x7056, "btlSetSpecialBattle", 1);
        putUnknownFunc(0x7057, "btlDirMove", 4);
        putUnknownFunc(0x7058, "btlCheckMotionNum", 2);
        putUnknownFunc(0x7059, "btlMoveTargetDist2D", "float", 1);
        putFuncWithIdx(0x705A, new ScriptFunc("forcePerformMove", "bool", "btlSetAbsCommand", p("target", "actor"), p("move")));
        putUnknownFunc(0x705B, "btlGetCamWidth", "float", 1);
        putUnknownFunc(0x705C, "btlGetCamHeight", "float", 1);
        putUnknownFunc(0x705D, "btlSetBindEffect", 2);
        putUnknownFunc(0x705E, "btlResetBindEffect", 0);
        putUnknownFunc(0x705F, "btlPrintF", 1);
        putUnknownFunc(0x7060, "btlSetStatEff", 0);
        putUnknownFunc(0x7061, "btlClearStatEff", 0);
        putUnknownFunc(0x7062, "btlSetHitEffect", 2);
        putUnknownFunc(0x7063, "btlWaitHitEffect", 0);
        putFuncWithIdx(0x7064, new ScriptFunc("loadBattleVoiceLine", "unknown", "btlVoiceStandby", p("voiceFileIndex", "int")));
        putUnknownFunc(0x7065, "btlVoiceStart", 0);
        putUnknownFunc(0x7066, "btlVoiceStop", 0);
        putUnknownFunc(0x7067, "btlGetVoiceStatus", 0);
        putUnknownFunc(0x7068, "btlVoiceSync", 0);
        putUnknownFunc(0x7069, "btlSearchChrCamera", 4);
        putUnknownFunc(0x706A, "btlCheckTargetOwn", 1);
        putUnknownFunc(0x706B, "btlSetModelHide", 3);
        putUnknownFunc(0x706C, "btlSoundEffectNormal", 2);
        putUnknownFunc(0x706D, "btlSoundStreamNormal", 2);
        putUnknownFunc(0x706E, "btlReqVoice", 2);
        putUnknownFunc(0x706F, "btlSetMotion2", 1);
        putUnknownFunc(0x7070, "btlStatusOn", 0);
        putUnknownFunc(0x7071, "btlStatusOff", 0);
        putFuncWithIdx(0x7072, new ScriptFunc("displayDialogueLine", "unknown", "btlmes2", p("boxIndex", "int"), p("string")));
        putUnknownFunc(0x7073, "btlAttachWeapon", 1);
        putUnknownFunc(0x7074, "btlDetachWeapon", 1);
        putUnknownFunc(0x7075, "btlReqWeaponMotion", 3);
        putUnknownFunc(0x7076, "btlBallSplineMove", 3);
        putUnknownFunc(0x7077, "btlDistTargetFrameBall", 2);
        putFuncWithIdx(0x7078, new ScriptFuncAccessor("readMovePropertyForActor", "move", "btlGetComInfo2", null, "moveProperty", p("actor")));
        putUnknownFunc(0x7079, "btlResetWeapon", 0);
        putUnknownFunc(0x707A, "btlGetCalcResult", 1);
        putUnknownFunc(0x707B, "btlSoundEffect", 2);
        putUnknownFunc(0x707C, "btlWaitSound", 0);
        putUnknownFunc(0x707D, "btlSetDebug", 2);
        putUnknownFunc(0x707E, "btlGetDebug", 1);
        putUnknownFunc(0x707F, "btlSetBtlPos", 1);
        putUnknownFunc(0x7080, "btlChangeAuron", 1);
        putUnknownFunc(0x7081, "btlWaitExe", 0);
        putUnknownFunc(0x7082, "btlSetFreeEffect", 2);
        putUnknownFunc(0x7083, "btlSetAfterImage", 2);
        putUnknownFunc(0x7084, "btlResetAfterImage", 0);
        putUnknownFunc(0x7085, "btlMoveAttack", 8);
        putUnknownFunc(0x7086, "btlUseChrMpLimit", 0);
        putUnknownFunc(0x7087, "btlSoundEffectFade", 3);
        putUnknownFunc(0x7088, "btlRegSoundEffect", 2);
        putUnknownFunc(0x7089, "btlRegSoundEffectFade", 3);
        putUnknownFunc(0x708A, "btlInitEncount", 1);
        putUnknownFunc(0x708B, "btlGetEncount", 1);
        putFuncWithIdx(0x708C, new ScriptFunc("setEncounterEnabled?", "unknown", "btlSetEncount", p("encounter"), p("active", "bool")));
        putUnknownFunc(0x708D, "btlGetLastActionChr", 0);
        putUnknownFunc(0x708E, "btlCheckBtlPos2", 0);
        putUnknownFunc(0x708F, "btlDirPosBasic", 1);
        putUnknownFunc(0x7090, "btlSetCriticalEffect", 1);
        putUnknownFunc(0x7091, "btlChangeChrName", 2);
        putUnknownFunc(0x7092, "btlGetGroundDist", 1);
        putUnknownFunc(0x7093, "btlCheckDirFlag", 0);
        putUnknownFunc(0x7094, "btlSetTransVisible", 3);
        putUnknownFunc(0x7095, "btlGetMoveFrameRest", 0);
        putUnknownFunc(0x7096, "btlGetReflect", 0);
        putFuncWithIdx(0x7097, new ScriptFunc("runBattleScriptB", "unknown", "btlOff2", p("index", "int")));
        putUnknownFunc(0x7098, "btlCheckDefenseMotion", 0);
        putUnknownFunc(0x7099, "btlSetCursorType", 1);
        putUnknownFunc(0x709A, "btlCheckPoison", 0);
        putUnknownFunc(0x709B, "btlGetChrPosY", "float", 1);
        putUnknownFunc(0x709C, "btlGetTargetDir", "float", 2);
        putUnknownFunc(0x709D, "btlWaitMotion_avoid", 0);
        putUnknownFunc(0x709E, "btlSetMotionSignal", 3);
        putUnknownFunc(0x709F, "btlGetChrTargetDir", "float", 1);
        putUnknownFunc(0x70A0, "btlSetUpVectorFlag", 1);
        putFuncWithIdx(0x70A1, new ScriptFunc("dereferenceEnemy", "actor", "btlGetChrNum2", p("actor")));
        putUnknownFunc(0x70A2, "btlMotionRead", 1);
        putUnknownFunc(0x70A3, "btlSetMotionAbs", 1);
        putUnknownFunc(0x70A4, "btlMotionDispose", 0);
        putUnknownFunc(0x70A5, "btlSetMapCenter", 3);
        putUnknownFunc(0x70A6, "btlSetEscape", 1);
        putUnknownFunc(0x70A7, "btlGetMotionData", "float", 2);
        putUnknownFunc(0x70A8, "btlSetMotionData", 3);
        putUnknownFunc(0x70A9, "btlmeswait_voice", 1);
        putFuncWithIdx(0x70AA, new ScriptFuncAccessor("readActorProperty2", null, "btlGetStat2", null, "actorProperty"));
        putFuncWithIdx(0x70AB, new ScriptFuncAccessor("setActorProperty2", null, "btlSetStat2", "=", "actorProperty"));
        putUnknownFunc(0x70AC, "btlGetMotionData2", "float", 1);
        putUnknownFunc(0x70AD, "btlCheckWakkaWeapon", 0);
        putUnknownFunc(0x70AE, "btlGetLastDeathChr", 0);
        putUnknownFunc(0x70AF, "btlGetVoiceFlag", 0);
        putUnknownFunc(0x70B0, "btlDistTargetFrame2", 1);
        putUnknownFunc(0x70B1, "btlPrintSp", 1);
        putUnknownFunc(0x70B2, "btlSetMotionData2", 2);
        putUnknownFunc(0x70B3, "btlVoiceSet", 1);
        putUnknownFunc(0x70B4, "btlFadeOutWeapon", 0);
        putUnknownFunc(0x70B5, "btlResetMotionSpeed", 0);
        putUnknownFunc(0x70B6, "btlDistTargetFrameSpd", 1);
        putUnknownFunc(0x70B7, "btlmesa", 2);
        putUnknownFunc(0x70B8, "btlSetSkipMode", 1);
        putUnknownFunc(0x70B9, "btlGetCamWidth2", "float", 1);
        putUnknownFunc(0x70BA, "btlGetCamHeight2", "float", 1);
        putUnknownFunc(0x70BB, "btlMoveLeave", 1);
        putUnknownFunc(0x70BC, "btlWaitNomEff", 1);
        putUnknownFunc(0x70BD, "btlWaitHitEff", 1);
        putUnknownFunc(0x70BE, "btlGetChrDir", "float", 1);
        putUnknownFunc(0x70BF, "btlSetBindScale", 1);
        putUnknownFunc(0x70C0, "btlGetHeight", "float", 1);
        putUnknownFunc(0x70C1, "btlDistTarget2", 2);
        putUnknownFunc(0x70C2, "btlGetTargetDirH", "float", 2);
        putUnknownFunc(0x70C3, "btlGetChrTargetDir2", "float", 1);
        putUnknownFunc(0x70C4, "btlEquipWakkaWeapon", 1);
        putUnknownFunc(0x70C5, "btlCheckRetBtlPos", 0);
        putUnknownFunc(0x70C6, "btlGetCameraBuffer", 1);
        putUnknownFunc(0x70C7, "btlGetCameraBufferFloat", "float", 1);
        putUnknownFunc(0x70C8, "btlSoundEffect2", 2);
        putUnknownFunc(0x70C9, "btlSoundEffect3", 2);
        putUnknownFunc(0x70CA, "btlRegSoundEffect2", 2);
        putUnknownFunc(0x70CB, "btlRegSoundEffect3", 2);
        putFuncWithIdx(0x70CC, new ScriptFunc("initializePredefinedGroupTo", "unknown", "btlSetOwnTarget", p("actor")));
        putFuncWithIdx(0x70CD, new ScriptFunc("addToPredefinedGroup", "unknown", "btlAddOwnTarget", p("actor")));
        putFuncWithIdx(0x70CE, new ScriptFunc("removeFromPredefinedGroup", "unknown", "btlSubOwnTarget", p("actor")));
        putUnknownFunc(0x70CF, "btlGetReverbe", 0);
        putUnknownFunc(0x70D0, "btlSetCameraSelectMode", 1);
        putUnknownFunc(0x70D1, "btlGetNomEff", 1);
        putUnknownFunc(0x70D2, "btlGetHitEff", 1);
        putUnknownFunc(0x70D3, "btlSetNomEff", 3);
        putUnknownFunc(0x70D4, "btlSetHitEff", 3);
        putFuncWithIdx(0x70D5, new ScriptFunc("setSummoner", "unknown", "btlSetSummoner", p("actor")));
        putUnknownFunc(0x70D6, "btlGetAssumeDamage", 3);
        putUnknownFunc(0x70D7, "btlSetDamageMotion", 2);
        putUnknownFunc(0x70D8, "btlSetAnimaChainOff", 1);
        putUnknownFunc(0x70D9, "btlExeAnimaChainOff", 0);
        putUnknownFunc(0x70DA, "btlGetFirstAttack", "ambushState", 0);
        putUnknownFunc(0x70DB, "btlGetAnimaChainOff", 0);
        putFuncWithIdx(0x70DC, new ScriptFunc("changeActorName", "unknown", "btlChangeChrNameID", p("actor"), p("string")));
        putUnknownFunc(0x70DD, "btlSetDebugCount", 1);
        putFuncWithIdx(0x70DE, new ScriptFunc("SubtitlesEnabled?", "bool", "btlGetSubTitle", false));
        putUnknownFunc(0x70DF, "btlCheckBtlScene", 1);
        putFuncWithIdx(0x70E0, new ScriptFunc("NotCounterattack", "bool", "btlGetReaction", false));
        putUnknownFunc(0x70E1, "btlGetNormalAttack", 0);
        putUnknownFunc(0x70E2, "btlSetTexAnime", 2);
        putUnknownFunc(0x70E3, "btlGetEffectMemory", 1);
        putUnknownFunc(0x70E4, "btlGetCalcResultLimit", 2);
        putUnknownFunc(0x70E5, "btlSetNomEffReg", 3);
        putUnknownFunc(0x70E6, "btlSetHitEffReg", 3);
        putUnknownFunc(0x70E7, "btlSetRandomTarget", 1);
        putFuncWithIdx(0x70E8, new ScriptFunc("PlayerTotalGil", "int", "btlGetGold", false));
        putFuncWithIdx(0x70E9, new ScriptFunc("YojimboHireAnswer", "int", "btlGetYoujinboType", false));
        putUnknownFunc(0x70EA, "btlSetYoujinboType", 1);
        putUnknownFunc(0x70EB, "btlGetYoujinboRandom", 0);
        putUnknownFunc(0x70EC, "btlGetItemNum", 1);
        putFuncWithIdx(0x70ED, new ScriptFunc("giveItem", "unknown", "btlGetItem", p("item", "move"), p("quantity", "int")));
        putFuncWithIdx(0x70EE, new ScriptFunc("RollYojimboMove", "move", "btlGetYoujinboCommand", p("motivation", "int"), p("unknown")));
        putUnknownFunc(0x70EF, "btlSetEffSignal", 2);
        putUnknownFunc(0x70F0, "btlGetCameraCount", "float", 0);
        putFuncWithIdx(0x70F1, new ScriptFunc("clearOwnMoves?", "unknown", "btlCommandClear", true));
        putFuncWithIdx(0x70F2, new ScriptFunc("addMoveToSelf?", "unknown", "btlCommandSet", p("move")));
        putFuncWithIdx(0x70F3, new ScriptFunc("RollMagusRandom", "bool", "btlCheckMegasRandom", p("unknown"), p("chance", "int")));
        putUnknownFunc(0x70F4, "btlGetCommandTarget", 2);
        putUnknownFunc(0x70F5, "btlCheckUseCommand", 2);
        putUnknownFunc(0x70F6, "btlInitCommandBuffer", 0);
        putUnknownFunc(0x70F7, "btlSetCommandBuffer", 1);
        putUnknownFunc(0x70F8, "btlGetCommandBuffer", 0);
        putUnknownFunc(0x70F9, "btlSearchChr3", 5);
        putUnknownFunc(0x70FA, "btlSetMegasRandomCommand", 1);
        putUnknownFunc(0x70FB, "btlGetCommandTargetSearch", 5);
        putUnknownFunc(0x70FC, "btlGetMegasRandomCommand", 0);
        putUnknownFunc(0x70FD, "btlSetUpLimit", 2);
        putUnknownFunc(0x70FE, "btlSetUpLimit2", 4);
        putUnknownFunc(0x70FF, "btlSetDeltaTarget", 0);
        putUnknownFunc(0x7100, "btlCheckReqMotion", 1);
        putUnknownFunc(0x7101, "btlGetFullCommand", 0);
        putFuncWithIdx(0x7102, new ScriptFunc("makeActorHeadFaceActor?", "unknown", "btlFaseTarget", p("actor"), p("target","actor")));
        putUnknownFunc(0x7103, "btlFaseTargetXYZ", 4);
        putUnknownFunc(0x7104, "btlSetCommandEffect", 3);
        putFuncWithIdx(0x7104, new ScriptFunc("changeMoveAnimation", "unknown", "btlSetCommandEffect", p("move"), p("anim1", "int"), p("anim2", "int")));
        putUnknownFunc(0x7105, "btlWaitStone", 0);
        putFuncWithIdx(0x7106, new ScriptFunc("doesActorKnowMove", "bool", "btlCheckGetCommand", p("actor"), p("move")));
        putUnknownFunc(0x7107, "btlDirPosBasic2", 1);
        putUnknownFunc(0x7108, "btlDirBasic2", 2);
        putUnknownFunc(0x7109, "btlSetAppear", 3);
        putUnknownFunc(0x710A, "btlSetSummonTiming", 0);
        putUnknownFunc(0x710B, "btlWaitSummonTiming", 0);
        putUnknownFunc(0x710C, "btlTerminateStone", 0);
        putUnknownFunc(0x710D, "btlDefensePosOff", 0);
        putUnknownFunc(0x710E, "btlGetWakkaLimitSkill", 0);
        putUnknownFunc(0x710F, "btlGetWakkaLimitNum", 0);
        putUnknownFunc(0x7110, "btlMouseOn", 1);
        putUnknownFunc(0x7111, "btlMouseOff", 1);
        putUnknownFunc(0x7112, "btlDirMove2", 4);
        putUnknownFunc(0x7113, "btlMonsterFarm", 0);
        putUnknownFunc(0x7114, "btlSphereMonitor", 0);
        putUnknownFunc(0x7115, "btlDirResetLeave", 0);
        putUnknownFunc(0x7116, "btlSetSummonDefenseEffect", 0);
        putFuncWithIdx(0x7117, new ScriptFunc("overrideDeathAnimationWithAction", "unknown", "btlSetDeathCommand", p("target", "actor"), p("move")));
        putUnknownFunc(0x7118, "btlSetSummonGameOver", 1);
        putUnknownFunc(0x7119, "btlSetCounterFlag", 1);
        putUnknownFunc(0x711A, "btlSetWind", 4);
        putUnknownFunc(0x711B, "btlSetCameraStandard", 0);
        putUnknownFunc(0x711C, "btlSetGameOverEffNum", 1);
        putUnknownFunc(0x711D, "btlSetShadowHeight", 1);
        putFuncWithIdx(0x7120, new ScriptFunc("displayBattleStringSimple?", "unknown", null, p("boxIndex", "int"), p("string")));
        putUnknownFunc(0x7123, 1);
        putUnknownFunc(0x7124, 1);
        putUnknownFunc(0x7125, 0);
        putUnknownFunc(0x7126, 1);
        putUnknownFunc(0x7127, 2);

        putFuncWithIdx(0x8000, new ScriptFunc("setLevelLayerVisibility", "unknown", null, p("layerIndex", "int"), p("visible", "bool")));
        putFuncWithIdx(0x8001, new ScriptFunc("setSkyboxVisibility", "unknown", null, p("visible", "bool")));
        putFuncWithIdx(0x8002, new ScriptFunc("setGfxActive?", "unknown", null, p("gfxIndex", "int"), p("active", "bool"))); // GFX are either lights or particle effects
        putFuncWithIdx(0x8003, new ScriptFunc("startGfxTimer", "unknown", null, p("gfxIndex", "int")));
        putFuncWithIdx(0x8004, new ScriptFunc("waitForGfxStopped", "unknown", null, p("gfxIndex", "int"))); // equivalent to 8005 with true
        putFuncWithIdx(0x8005, new ScriptFunc("waitForGfxEnding", "unknown", null, p("gfxIndex", "int"), p("waitForChildren", "bool")));
        putUnknownFunc(0x8006, 1);
        putFuncWithIdx(0x8007, new ScriptFunc("setAllGfxActive", "unknown", null, true));
        putFuncWithIdx(0x8008, new ScriptFunc("stopAllGfx", "unknown", null, true));
        putFuncWithIdx(0x8009, new ScriptFunc("bindGfxToTarget", "unknown", null, p("gfxIndex", "int"), p("target", "int"))); // for actors, target is a bone index
        putFuncWithIdx(0x800A, new ScriptFunc("bindGfxPosition", "unknown", "mpfpbindpos", p("gfxIndex", "int"), p("x", "float"), p("y", "float"), p("z", "float")));
        putFuncWithIdx(0x800B, new ScriptFunc("unbindGfx", "unknown", null, p("gfxIndex", "int")));
        putFuncWithIdx(0x800C, new ScriptFunc("setGfxEnabledGlobal", "unknown", null, p("enabled", "bool"))); // controls all gfx rendering/updates 
        putFuncWithIdx(0x800D, new ScriptFunc("setGfxVisibility", "unknown", null, p("gfxIndex", "int"), p("visible", "bool")));
        // next several are about the image planes used for forced-perspective areas
        putUnknownFunc(0x800F, 1); // clear image hidden flag
        putUnknownFunc(0x8010, 1); // set image hidden flag
        putUnknownFunc(0x8011, 3); 
        putUnknownFunc(0x8014, 2); // set image depth
        putUnknownFunc(0x801D, 2);
        putUnknownFunc(0x801E, 1);
        putUnknownFunc(0x801F, 1);
        putUnknownFunc(0x8020, 1);
        putUnknownFunc(0x8021, 1);
        putUnknownFunc(0x8022, 2);
        putUnknownFunc(0x8026, 5);
        putUnknownFunc(0x802C, 0);
        putUnknownFunc(0x802D, 0);
        putUnknownFunc(0x802E, 2);
        putUnknownFunc(0x802F, 1);
        putUnknownFunc(0x8030, 2); // set image opacity
        putUnknownFunc(0x8032, 1); // minimap related?
        putFuncWithIdx(0x8035, new ScriptFunc("setGfxGroupActive", "unknown", null, p("group", "int"), p("active", "bool")));
        putFuncWithIdx(0x8036, new ScriptFunc("setGfxGroupVisibility", "unknown", null, p("group", "int"), p("visible", "bool")));
        putUnknownFunc(0x8037, 3); // set global scale?
        putUnknownFunc(0x8038, 1); // set/get scale components
        putUnknownFunc(0x8039, 0);
        putUnknownFunc(0x803A, 1);
        putUnknownFunc(0x803B, 0);
        putUnknownFunc(0x803C, 1);
        putUnknownFunc(0x803D, 0);
        putFuncWithIdx(0x803E, new ScriptFunc("setFogColor", "unknown", null, p("red", "int"), p("green", "int"), p("blue", "int")));
        putFuncWithIdx(0x803F, new ScriptFunc("setFogRed", "unknown", null, p("red", "int")));
        putFuncWithIdx(0x8040, new ScriptFunc("setFogGreen", "unknown", null, p("green", "int")));
        putFuncWithIdx(0x8041, new ScriptFunc("setFogBlue", "unknown", null, p("blue", "int")));
        putFuncWithIdx(0x8042, new ScriptFunc("getFogRed", "int", null, true));
        putFuncWithIdx(0x8043, new ScriptFunc("getFogGreen", "int", null, true));
        putFuncWithIdx(0x8044, new ScriptFunc("getFogBlue", "int", null, true));
        putFuncWithIdx(0x8045, new ScriptFunc("setClearColor", "unknown", null, p("red", "int"), p("green", "int"), p("blue", "int")));
        putUnknownFunc(0x8049, 0);
        putUnknownFunc(0x804A, 0);
        putUnknownFunc(0x804B, 0);
        putUnknownFunc(0x804F, 3);
        putFuncWithIdx(0x8059, new ScriptFunc("bindGfxToMapGroup", "unknown", null, p("gfxIndex", "int"), p("groupIndex", "int")));
        putFuncWithIdx(0x805B, new ScriptFunc("setGfxPosition", "unknown", null, p("gfxIndex", "int"), p("x", "float"), p("y", "float"), p("z", "float")));
        putUnknownFunc(0x805C, 1);
        putUnknownFunc(0x805D, 0);
        putUnknownFunc(0x805E, 1);
        putFuncWithIdx(0x805F, new ScriptFunc("stopGfx", "unknown", null, p("gfxIndex", "int")));
        putFuncWithIdx(0x8060, new ScriptFunc("stopGfxGroup", "unknown", null, p("groupIndex", "int")));
        putFuncWithIdx(0x8066, new ScriptFunc("setGfxPausedGlobal", "unknown", null, p("paused", "bool")));
        putUnknownFunc(0x8067, 4);
        putUnknownFunc(0x806A, 1); // set an image plane's map group
        putUnknownFunc(0x806B, 1); // totally empty?!
        putUnknownFunc(0xB000, 2); // Inference based on A2 popping 1 and pushing 1
        putUnknownFunc(0xB001, 0);
        putUnknownFunc(0xB002, 0);
        putUnknownFunc(0xB003, 0);
        putUnknownFunc(0xB004, 0);
        putUnknownFunc(0xB009, 0);
        putUnknownFunc(0xB00A, 2);
        putUnknownFunc(0xB00B, 0);
        putUnknownFunc(0xB00C, 0);
        putUnknownFunc(0xB00D, 0);
        putUnknownFunc(0xC002, 1);
        putUnknownFunc(0xC003, 1);
        putUnknownFunc(0xC007, 2);
        putUnknownFunc(0xC009, 1);
        putUnknownFunc(0xC00B, 1);
        putUnknownFunc(0xC00C, 1);
        putUnknownFunc(0xC00D, 1);
        putUnknownFunc(0xC013, 0);
        putUnknownFunc(0xC014, 0);
        putUnknownFunc(0xC018, 1);
        putUnknownFunc(0xC022, 1);
        putFuncWithIdx(0xC024, new ScriptFunc("launchBattleAlwaysWin?", "unknown", null, p("encounter"), p("transition?", "battleTransition")));
        putUnknownFunc(0xC025, 1);
        putUnknownFunc(0xC028, 0);
        putUnknownFunc(0xC02A, 1);
        putUnknownFunc(0xC02C, 1);
        putUnknownFunc(0xC02F, 2);
        putUnknownFunc(0xC030, 0);
        putUnknownFunc(0xC031, 1);
        putUnknownFunc(0xC036, 1);
        putUnknownFunc(0xC03B, 0);
        putUnknownFunc(0xC03C, 0);
        putUnknownFunc(0xC051, 1);
        putUnknownFunc(0xC052, 0);
        putUnknownFunc(0xC053, 4);
        putUnknownFunc(0xC054, 1);
        putUnknownFunc(0xC055, 1);
        putUnknownFunc(0xC056, 3);
        putUnknownFunc(0xC057, 1);
        putUnknownFunc(0xC058, 1);
        putUnknownFunc(0xC05B, 1);
    }
}
